name: Main Workflow

on:
  push:
    branches:
      - '**'

jobs:
  deploy-preview:
    uses: ./.github/workflows/deploy-preview.yml

  playwright-test:
    needs: deploy-preview
    uses: ./.github/workflows/playwright-test.yml
