name: Main Workflow

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-preview.yml

  test:
    needs: deploy
    uses: ./.github/workflows/playwright-test.yml
