name: Main Workflow

on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    uses: ./.github/workflows/deploy-preview.yml

  playwright-test:
    needs: build-and-deploy
    uses: ./.github/workflows/playwright-test.yml
