name: Playwright Tests

on:
  workflow_call:
    inputs:
      preview_url:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set preview URL
        run: echo "PREVIEW_URL=${{ inputs.preview_url }}" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        working-directory: ./playwright
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./playwright
        env:
          PREVIEW_BASE_URL: ${{ env.PREVIEW_URL }}
        run: |
          echo "Running tests against $PREVIEW_BASE_URL"
          npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30